services:
  - type: web
    name: nexus-admin-backend
    env: node
    branch: main
    root: .
    buildCommand: |
      pwd
      echo "--- list root ---"
      ls -la
      echo "--- list src (if present) ---"
      ls -la src || true
      echo "--- continue install ---"
      npm ci --production
    startCommand: node server.js
    plan: free
